services:
  frontend:
    build:
      context: github.com/cedigasser/deweb
      dockerfile: Dockerfile.frontend
      args:
        PUBLIC_BACKEND_URL: http://localhost
    container_name: deweb-frontend
    expose:
      - 443
    ports:
      - '443:443'
      - '80:80'

  backend:
    build:
      context: github.com/cedigasser/deweb
      dockerfile: Dockerfile.backend
    container_name: backend
    expose:
      - 8000
