# syntax=docker/dockerfile:1

FROM denoland/deno:latest AS builder
WORKDIR /app
COPY ./frontend/package.json ./frontend/deno.lock ./frontend/svelte.config.js ./
RUN deno install
COPY ./frontend .
ARG PUBLIC_BACKEND_URL
ENV PUBLIC_BACKEND_URL=$PUBLIC_BACKEND_URL
RUN deno task build 

FROM nginx:latest
COPY ./frontend/nginx/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/build /usr/share/nginx/html/